sources:
  - name: canopyapi
    handler:
      graphql:
        endpoint: "https://www.universe.com/graphql"
  - name: tcgdex
    handler:
      graphql:
        endpoint: "https://api.tcgdex.net/v2/graphql"

serve:
  endpoint: /api/graphql
  port: 4001
